// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fspavyajmtykzyzprnvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcGF2eWFqbXR5a3p5enBybnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzIzODMsImV4cCI6MjA2NjAwODM4M30.7YnaDvcgZZsE2NPAfH7AD_pp7HEscfEY6Sh9ESGxb7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);